name: Create and publish a Docker image

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-containers:
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-2019, windows-2022]
        include:
        - os: ubuntu-latest
          base: 6.0-bullseye-slim-amd64
          tag: linux
        - os: windows-2019
          base: 6.0-windowsservercore-ltsc2019
          tag: windows-ltsc2019-amd64
        - os: windows-2022
          base: 6.0-nanoserver-ltsc2022
          tag: windows-ltsc2022-amd64
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: imageName
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ env.IMAGE_NAME }}
      - name: Docker Build
        run: |
          docker build --build-arg BASE=${{ matrix.base }} -t ${{ env.REGISTRY }}/${{ steps.imageName.outputs.lowercase }}:${{ matrix.tag }} .
      - name: Docker Push
        run: |
          docker push ${{ env.REGISTRY }}/${{ steps.imageName.outputs.lowercase }}:${{ matrix.tag }}